site_name: PathfindingModule
site_url: https://github.com/xcvbwer123-rs/PathfindingModule
site_description: PathfindingModule을 위한 자료
site_author: xcvbwer123

docs_dir: src
site_dir: docs

repo_name: xcvbwer123-rs/PathfindingModule
repo_url: https://github.com/xcvbwer123-rs/PathfindingModule

lang: multi
min_search_length: 2

theme:
  name: material
  palette:
    primary: blue grey
    accent: blue grey
  logo: images/logo.png
  favicon: images/favicon.jpg
  

nav:
  - Home: index.md
  - Guide: 
    - Installation: GetStarted/installation.md
    - Basic Usage: GetStarted/basic_usage.md
    - "Basic Example: Following NPC": GetStarted/example_following_ai.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true